---
# Development environment override
services:
  php:
    build:
      context: .
      target: frankenphp_dev
    volumes:
      - ./:/app
      - jwt_keys:/var/jwt
      - ./frankenphp/Caddyfile:/etc/frankenphp/Caddyfile:ro
      - ./frankenphp/conf.d/20-app.dev.ini:/usr/local/etc/php/app.conf.d/20-app.dev.ini:ro
      # If you develop on Mac or Windows you can remove the vendor/ directory
      #  from the bind-mount for better performance by enabling the next line:
      #- /app/vendor
    environment:
      FRANKENPHP_WORKER_CONFIG: watch
      MERCURE_EXTRA_DIRECTIVES: demo
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
      APP_ENV: "${APP_ENV:-dev}"
      APP_DEBUG: "${APP_DEBUG:-1}"
      JWT_PASSPHRASE: "${JWT_PASSPHRASE:-}"
      JWT_ACCESS_TTL: "${JWT_ACCESS_TTL:-3600}"
      JWT_REFRESH_TTL: "${JWT_REFRESH_TTL:-2592000}"
      PASSWORD_RESET_TOKEN_TTL: "${PASSWORD_RESET_TOKEN_TTL:-3600}"
      # Force dev reset-link to local frontend
      PASSWORD_RESET_URL_TEMPLATE: "http://localhost:8100/auth/reset-password/confirm?token=%s"
      MAILER_FROM: "${MAILER_FROM:-no-reply@localhost}"
      # For local dev force Mailpit; avoid null://null from env
      MAILER_DSN: "smtp://mailer:1025"
      # Dev-Mode: Verwende andere Ports, um Konflikte mit anderen Dev-Prozessen zu vermeiden
      HTTP_PORT: "${HTTP_PORT:-8080}"
      HTTPS_PORT: "${HTTPS_PORT:-8443}"
      HTTP3_PORT: "${HTTP3_PORT:-8443}"
      MERCURE_PUBLIC_URL: "${MERCURE_PUBLIC_URL:-https://${SERVER_NAME:-localhost}:${HTTPS_PORT:-8443}/.well-known/mercure}"
    # Dev-Mode: Überschreibe Ports für Dev-Umgebung
    # Hinweis: Docker Compose kombiniert Ports-Arrays, daher werden beide gemappt
    # Die Dev-Ports (8080/8443) sollten verwendet werden
    ports:
      - target: 80
        published: ${HTTP_PORT:-8080}
        protocol: tcp
      - target: 443
        published: ${HTTPS_PORT:-8443}
        protocol: tcp
      - target: 443
        published: ${HTTP3_PORT:-8443}
        protocol: udp
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
    tty: true
###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432:5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###
