---
# Production environment override
services:
  php:
    build:
      context: .
      target: frankenphp_prod
    env_file:
      - ./compose.env
    environment:
      APP_SECRET: ${APP_SECRET}
      JWT_PASSPHRASE: ${JWT_PASSPHRASE}
      JWT_ACCESS_TTL: ${JWT_ACCESS_TTL:-3600}
      JWT_REFRESH_TTL: ${JWT_REFRESH_TTL:-2592000}
      PASSWORD_RESET_TOKEN_TTL: ${PASSWORD_RESET_TOKEN_TTL:-3600}
      PASSWORD_RESET_URL_TEMPLATE: ${PASSWORD_RESET_URL_TEMPLATE:-http://194.35.120.105/auth/reset-password/confirm?token=%s}
      MAILER_DSN: ${MAILER_DSN}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      DATABASE_URL: postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-!ChangeMe!}@database:5432/${POSTGRES_DB:-app}?serverVersion=${POSTGRES_VERSION:-16}&charset=utf8
    # Production: Standard-Ports
    ports:
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
